<a href="https://colab.research.google.com/github/nickroh/datascience/blob/master/5_18%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


arr=np.array([[2,3,1],[4,5,8]])
arr2=np.array([[1],[2],[3]])

result=arr.dot(arr2)

print(result)

w=0
a=0.5

for i in range(4):
  dw = w -1
  w = w - a*dw
  
print(w)

x = np.array([1,2,3])
w = 5
H = sum(w*x)/len(x)
print(x.shape)

[[11]
 [38]]
0.9375
(3,)


In [2]:
import numpy as np
X = np.array([[30,10,5,1],[20,20,10,1],[40,30,15,1]])
t = np.array([6.1, 3.1, 6.8]).reshape(3,1)
W = np.array([1, 0, 0, 0]).reshape(4,1) #초기 매개변수
print(X.T)
print(t.shape)
print(W)
a = 0.0001 # 학습률
Y = np.dot(X,W)
print(Y)
print(Y-t)
print(t.shape[0])
for k in range(3000):
  dW = 2*(np.dot(X.T,(Y-t)))/t.shape[0] #그래디언트 ---- 채우시오
  W = W - a*dW #행렬의 뺄셈을 이용하여 한꺼번에 처리
  J = np.dot((Y-t),(Y-t).T)/Y.shape[1] #전치행렬 이용하여 제곱처리
  Y = np.dot( X,W)
  if k % 100 == 0:
    #print(W) # 매개변수의 변화 관찰
    print('Iteration:', k, 'MSE:', J[0,0])

print('')
X_test = np.array([[25], [20], [10],[1]]).T # 25평, 20분 거리, 10년 된 건물
print("Price Prediction:", (np.dot(X_test, W))) #학습된 모델 이용 예측
print(W)

[[30 20 40]
 [10 20 30]
 [ 5 10 15]
 [ 1  1  1]]
(3, 1)
[[1]
 [0]
 [0]
 [0]]
[[30]
 [20]
 [40]]
[[23.9]
 [16.9]
 [33.2]]
3
Iteration: 0 MSE: 571.2099999999999
Iteration: 100 MSE: 2.776131261173772
Iteration: 200 MSE: 0.5053855808392163
Iteration: 300 MSE: 0.0871896281178584
Iteration: 400 MSE: 0.013100062566391036
Iteration: 500 MSE: 0.0012813887742631782
Iteration: 600 MSE: 2.5280361301538413e-06
Iteration: 700 MSE: 0.0001762235493043537
Iteration: 800 MSE: 0.0003890425509076042
Iteration: 900 MSE: 0.0005067768749041944
Iteration: 1000 MSE: 0.000561976373197985
Iteration: 1100 MSE: 0.00058598774345318
Iteration: 1200 MSE: 0.0005956888412073719
Iteration: 1300 MSE: 0.0005990301489382117
Iteration: 1400 MSE: 0.0005995831018560309
Iteration: 1500 MSE: 0.0005989216833035833
Iteration: 1600 MSE: 0.0005977340113705377
Iteration: 1700 MSE: 0.0005963198786929888
Iteration: 1800 MSE: 0.0005948096973087957
Iteration: 1900 MSE: 0.0005932601570011398
Iteration: 2000 MSE: 0.0005916958901312916
Ite